[package]
name = "style_this"
version = "0.1.0"
authors = ["shiro <shiro@usagi.io>"]
edition = "2024"

[package.metadata.wasm-pack.profile.release]
# wasm-opt = ["-Os", "--enable-mutable-globals"]
wasm-opt = false

[package.metadata.wasm-pack.profile.dev]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.105"
wasm-bindgen-futures = "0.4.55"
thiserror = "2.0.17"
futures = "0.3.31"
async-std = "1.13.2"
indoc = "2.0.7"

oxc_parser = "0.95.0"
oxc_allocator = "0.95.0"
oxc_span = "0.95.0"
oxc_codegen = "0.95.0"
oxc_transformer = "0.95.0"
oxc_semantic = "0.95.0"
oxc_ast = "0.95.0"
oxc_ast_visit = "0.95.0"
oxc_syntax = "0.95.0"
oxc_sourcemap = "6.0.1"

js-sys = "0.3.82"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.55"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
